// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZaemeru16VTYWGD3wS6HnAOlXV_lDPLo',
    appId: '1:236840659581:web:96f6dcee5da44833f7df14',
    messagingSenderId: '236840659581',
    projectId: 'chatapp-5dedc',
    authDomain: 'chatapp-5dedc.firebaseapp.com',
    storageBucket: 'chatapp-5dedc.appspot.com',
    measurementId: 'G-6GQTTELDLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANO6OodI9bjBE66kM8omsoCozHcGOFR3Y',
    appId: '1:236840659581:android:5d63548fb04a598bf7df14',
    messagingSenderId: '236840659581',
    projectId: 'chatapp-5dedc',
    storageBucket: 'chatapp-5dedc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH7EFniRSV0yBL01SeDTWxRFHpgjZb2cg',
    appId: '1:236840659581:ios:09bb0267a6cffa48f7df14',
    messagingSenderId: '236840659581',
    projectId: 'chatapp-5dedc',
    storageBucket: 'chatapp-5dedc.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH7EFniRSV0yBL01SeDTWxRFHpgjZb2cg',
    appId: '1:236840659581:ios:f2796a3966afccbbf7df14',
    messagingSenderId: '236840659581',
    projectId: 'chatapp-5dedc',
    storageBucket: 'chatapp-5dedc.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
